services:
  mongo_dev:
    image: mongo
    restart: always
    container_name: "mongo_dev"

    volumes:
      # Data Storage
      - ./data/mongo_dev:/data/db

      # Define Time
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/